apiVersion: v1
kind: Service
metadata:
  name: service-buyfeedback
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8082
  selector:
    app: buyfeedback-pod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buyfeedback-pod
  labels:
    app: buyfeedback-pod
spec:
  selector:
    matchLabels:
      app: buyfeedback-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: buyfeedback-pod
    spec:
      containers:
      - image: douglasnogueiram/ms-communication-buyfeedback:1.0.0.-SNAPSHOT
        name: buyfeedback-pod
        env:
        - name: SPRING_RABBITMQ_HOST
          value: "rs-rmq-mgt"
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: "rabbit666"
        - name: SPRING_RABBITMQ_PASSWORD
          value: "melhorsenhadomundo"
        - name: FILA_FINALIZADO
          value: "fila-compras-finalizado"
        - name: SPRING_REDIS_HOST
          value: "redis"
        - name: SPRING_REDIS_PORT
          value: "6379"
        - name: BANK_LINK
          value: "http://service-bank:8090/pagamento"
        - name: SERVER_PORT
          value: "8082"
        ports:
        - containerPort: 8082
          name: http