---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buyprocess-pod-v2
  labels:
    app: buyprocess-pod
    version: v2
spec:
  selector:
    matchLabels:
      app: buyprocess-pod
      version: v2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: buyprocess-pod
        version: v2
    spec:
      containers:
      - image: douglasnogueiram/ms-communication-buyprocess:1.0.0.-SNAPSHOT
        name: buyprocess-pod
        env:
        - name: SPRING_RABBITMQ_HOST
          value: "rs-rmq-mgt"
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: "rabbit666"
        - name: SPRING_RABBITMQ_PASSWORD
          value: "melhorsenhadomundo"
        - name: FILA_ENTRADA
          value: "fila-compras-aguardando"
        - name: FILA_FINALIZADO
          value: "fila-compras-finalizado"
        - name: BANK_LINK
          value: "http://service-bank:8090/pagamento"
        - name: SERVER_PORT
          value: "8081"
        ports:
        - containerPort: 8081
          name: http