---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: buytrip-pod-v2
  labels:
    app: buytrip-pod
    version: v2
spec:
  selector:
    matchLabels:
      app: buytrip-pod
      version: v2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: buytrip-pod
        version: v2
    spec:
      containers:
      - image: douglasnogueiram/ms-communication-buytrip:1.0.0.-SNAPSHOT
        name: buytrip-pod
        env:
        - name: SPRING_RABBITMQ_HOST
          value: "rs-rmq-mgt"
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: "rabbit666"
        - name: SPRING_RABBITMQ_PASSWORD
          value: "melhorsenhadomundo"
        - name: FILA_SAIDA
          value: "fila-compras-aguardando"
        - name: SERVER_PORT
          value: "8086"
        ports:
        - containerPort: 8086
          name: http