apiVersion: v1
kind: Service
metadata:
  name: rs-rmq-mgt
spec:
  selector:
    app: rs-rmq
  ports:
  - name: http
    port: 15672
    targetPort: 15672
  - name: aqmp
    port: 5672
    targetPort: 5672
  - name: epmd
    port: 4369
    targetPort: 4369
  - name: 25672-tcp
    port: 25672
    protocol: TCP
    targetPort: 25672
  type: NodePort  
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rs-rmq
spec:
  selector:
    matchLabels:
      app: rs-rmq
  serviceName: "rs-rmq"
  replicas: 1
  template:
    metadata:
      labels:
        app: rs-rmq
    spec:
      containers:
      - name: rs-rmq
        image: rabbitmq:management
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: "rabbit666"
          - name: RABBITMQ_DEFAULT_PASS
            value: "melhorsenhadomundo"
        ports:
        - containerPort: 25672
        - containerPort: 5672
        - containerPort: 4369
        - containerPort: 15672